// microfrontends/angular-widget/src/app/modal/modal.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-modal',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './modal.component.html',
})
export class ModalComponent {
  @Input() buttonText  = 'Open Modal'
  @Input() actionText = 'Yay!'
  @Input() title = 'Welcome'
}

<label for="my-modal" class="btn">{{ buttonText }}</label>
<input type="checkbox" id="my-modal" class="modal-toggle" />
<div class="modal">
  <div class="modal-box">
    <h3 class="font-bold text-lg">{{ title }}</h3>
    <ng-content></ng-content>
    <div class="modal-action">
      <label for="my-modal" class="btn">{{ actionText }}</label>
    </div>
  </div>
</div>

// microfrontends/vue-widget/src/components/Modal.vue
<template>
  <label for="my-modal" class="btn">open modal</label>
  <input type="checkbox" id="my-modal" class="modal-toggle" />
  <div class="modal">
    <div class="modal-box">
      <h3 class="font-bold text-lg">Congratulations random Internet user!</h3>
      <p class="py-4">
        You've been selected for a chance to get one year of subscription to use
        Wikipedia for free!
      </p>
      <div class="modal-action">
        <label for="my-modal" class="btn">Yay!</label>
      </div>
    </div>
  </div>
</template>
